### ISSUE TITLE
ReferenceError: google is not defined

### ISSUE THREAD

**Issue by sbasi5576** [israelidanny/ion-google-place#56]
I am getting the following in my console - Reference Error 

ReferenceError: google is not defined
    at link (http://localhost:8100/lib/ion-google-place/ion-google-place.js:17:40)
    at nodeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:14336:13)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13730:13)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13733:13)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13733:13)
    at nodeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:14330:24)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13730:13)
    at nodeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:14330:24)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13730:13)
    at compositeLinkFn (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13733:13) <input type="text" readonly="readonly" class="ion-google-place ng-pristine ng-valid" autocomplete="off" placeholder="Enter an address, Apt# and ZIP" ng-model="data.postal">

<label class="item item-input">
                    <span class="input-label">Purchase Location</span>

<ion-google-place placeholder="Enter an address, Apt# and ZIP" ng-model="location" />
                </label>

**Comment by sbasi5576** [comment]
Actually I just got it working.   Need to point to the css and js files in my index.html.
